### ISSUE TITLE
annotation file

### ISSUE THREAD

**Issue by Egorkasq** [adions025/Damage_Detection_MaskRCNN#1]
Hello, Is there datasets and annotation file in open access? Can I use it in my bachelor thesis?

**Comment by adions025** [comment]
It' s from the university but I could ask. Are you still interested?

**Comment by Egorkasq** [comment]
Yes of course

**Comment by Egorkasq** [comment]
> It' s from the university but I could ask. Are you still interested?

Yes of course

**Comment by ZHANGKEON** [comment]
Hello, I am interested in the dataset and annotation. I am wondering whether it could be shared? It will only be used for research purpose. Thanks.

**Comment by mozhuqing** [comment]
> It' s from the university but I could ask. Are you still interested?

hi, i am interested in this datasets, could u pls let me use it? I am doing a turbon research project

**Comment by adions025** [comment]
The dataset cannot be shared.
